# Generated by Django 5.2.12 on 2026-03-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='leitor',
            options={'verbose_name': 'Leitor', 'verbose_name_plural': 'Leitores'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do autor'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.CharField(default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da editora'),
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.CharField(default='', max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='CPF do leitor'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(default='', verbose_name='Data de publicação do livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.editora', verbose_name='Editora do livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genero', verbose_name='Gênero do livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(default='', verbose_name='Preço do livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default='', verbose_name='Status do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.autor', verbose_name='Autor do livro'),
        ),
    ]
