# Generated by Django 5.2.12 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_autor_options_alter_cidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(default='MG', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(default='oi.com', max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(default='12312312312', max_length=11, unique=True, verbose_name='CPF do leitor'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.CharField(default='banana@bananinha.com', max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(default='01/01/0001', verbose_name='Data de publicação do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(default='2', verbose_name='Preço do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default='0', verbose_name='Status do livro'),
        ),
    ]
