# Generated by Django 5.2.12 on 2026-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cidade_uf_alter_editora_site_alter_leitor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF do leitor'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(blank=True, verbose_name='Data de publicação do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(blank=True, verbose_name='Preço do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(blank=True, verbose_name='Status do livro'),
        ),
    ]
