# Generated by Django 5.2.12 on 2026-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cidade_uf_alter_editora_site_alter_leitor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF do leitor'),
        ),
    ]
