# Generated by Django 5.2.12 on 2026-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_leitor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF do leitor'),
        ),
    ]
